package com.demo_bank_v1.helper;

public class HTML {
	
	public static String HTMLEmailTemplate(String token, String code) {
		String url = "http://localhost:8070/verify?token="+token+"&code="+code;
		String emailTemplate = "<!DOCTYPE html>\r\n"
				+ "<html lang='en'>\r\n"
				+ "<head>\r\n"
				+ "    <meta charset='UTF-8'>\r\n"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n"
				+ "    <link rel=\'preconnect\' href=\'https://fonts.gstatic.com\'>\r\n"
				+ "    <link href=\'https://fonts.googleapis.com/css2?family=Comfortaa\' rel=\'stylesheet\'>\r\n"
				+ "    <title>Email</title>\r\n"
				+ "    <style>\r\n"
				+ "        * {\r\n"
				+ "            box-sizing: border-box;\r\n"
				+ "            font-family: Comfortaa;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        body {\r\n"
				+ "            height: 100vh;\r\n"
				+ "            background-color: rgb(186, 221, 225);\r\n"
				+ "            display: flex;\r\n"
				+ "            align-items: center;\r\n"
				+ "            justify-content: center;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        .wrapper {\r\n"
				+ "            width: 550px;\r\n"
				+ "            height: auto;\r\n"
				+ "            padding: 15px;\r\n"
				+ "            background-color: white;\r\n"
				+ "            border-radius: 7px;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        /* Email Message Header */\r\n"
				+ "        .email-message-header {\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        /* Company Name */\r\n"
				+ "        .company-name {\r\n"
				+ "            text-align: center;\r\n"
				+ "            font-size: 35px;\r\n"
				+ "            color: gray;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        /* Welcome Text */\r\n"
				+ "        .welcome-text {\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        /* Verify Account Button */\r\n"
				+ "        .verify-account-btn {\r\n"
				+ "            padding: 15px;\r\n"
				+ "            background-color: rgb(37, 73, 255);\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            color: white;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "        }\r\n"
				+ "    \r\n"
				+ "        /* Copy Right Wrapper */\r\n"
				+ "        .copy-right {\r\n"
				+ "            text-align: center;\r\n"
				+ "            padding: 15px;\r\n"
				+ "            color: gray;\r\n"
				+ "            font-size: 14px;\r\n"
				+ "            margin: 20px 0px;\r\n"
				+ "            display: flex;\r\n"
				+ "            align-items: center;\r\n"
				+ "            justify-content: center;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <!-- Wrapper -->\r\n"
				+ "    <div class='wrapper'>\r\n"
				+ "        <!-- Email Message Header -->\r\n"
				+ "        <h2 class='email-message-header'>\r\n"
				+ "            Welcome and Thank you for choosing\r\n"
				+ "        </h2>\r\n"
				+ "        <!-- End of Email Message Header -->\r\n"
				+ "\r\n"
				+ "        <!-- Company Name -->\r\n"
				+ "        <div class='company-name'>Banking Demo App</div>\r\n"
				+ "        <!-- End of Company Name -->\r\n"
				+ "        <hr>\r\n"
				+ "\r\n"
				+ "        <!-- Welcome Text -->\r\n"
				+ "        <p class='welcome-text'>\r\n"
				+ "            Your Account has been successfully registered, please click below to verify your account\r\n"
				+ "        </p>\r\n"
				+ "        <!-- End of Welcome Text -->\r\n"
				+ "        <br>\r\n"
				+ "        <br>\r\n"
				+ "\r\n"
				+ "        <!-- Verify Account Button -->\r\n"
				+ "        <center><a href='"+url+"' class='verify-account-btn'>Verify Account</a></center>\r\n"
				+ "        <!-- End of Verify Account Button -->\r\n"
				+ "\r\n"
				+ "        <!-- Copy Right Wrapper -->\r\n"
				+ "        <div class='copy-right'>\r\n"
				+ "            &copy; Copy Right 2024. All Rights Reserved.\r\n"
				+ "        </div>\r\n"
				+ "        <!-- End of Copy Right Wrapper -->\r\n"
				+ "    </div>\r\n"
				+ "    <!-- End of Wrapper -->\r\n"
				+ "</body>\r\n"
				+ "</html>";
		
		
		return emailTemplate;
	}

}
